import json
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from fastapi.testclient import TestClient

from app.models.schemas import (
    DenialExtractionResult,
    RegulationEntry,
    RegulatoryLookupResult,
)


SAMPLE_DENIAL_TEXT = """HealthFirst Insurance Company
Claims Department

Date: January 15, 2026

Patient Name: Jane Smith
Member ID: HF-2026-88421
Provider: Dr. Robert Chen, MD
Provider NPI: 1234567890
Claim Number: CLM-2026-00142

Date of Service: December 20, 2025
Procedure Code: CPT 27447 (Total Knee Arthroplasty)

REASON FOR DENIAL:
Your claim has been denied because prior authorization was not obtained.

CARC: 197
RARC: N56

Plan Type: ACA Marketplace (Silver Plan)

Appeal deadline: 180 days from date of denial.
"""

# This is what Gemini returns (float confidence) — extraction.py converts to string
SAMPLE_EXTRACTION_JSON = {
    "carc_code": "197",
    "rarc_code": "N56",
    "denied_cpt_codes": ["27447"],
    "denial_reason": "Prior authorization was not obtained before the service was rendered.",
    "denial_type": "prior_authorization",
    "plan_type": "ACA Marketplace",
    "patient_name": "Jane Smith",
    "patient_id": "HF-2026-88421",
    "provider_name": "Dr. Robert Chen, MD",
    "provider_npi": "1234567890",
    "insurance_company": "HealthFirst Insurance Company",
    "insurer_address": "P.O. Box 12345, Philadelphia, PA 19101",
    "claim_number": "CLM-2026-00142",
    "date_of_service": "2025-12-20",
    "date_of_denial": "2026-01-15",
    "appeal_deadline": "180 days from date of denial",
    "confidence": 0.95,
}

SAMPLE_APPEAL_LETTER = """Dear HealthFirst Insurance Company Appeals Department,

I am writing to formally appeal the denial of claim CLM-2026-00142 for patient Jane Smith (Member ID: HF-2026-88421).

The denied service, CPT 27447 (Total Knee Arthroplasty), was performed on December 20, 2025 by Dr. Robert Chen, MD (NPI: 1234567890).

Your denial, issued January 15, 2026, cites CARC 197 as the reason. Under 42 USC 300gg-19, group and individual health coverage must provide internal claims appeals and external review processes.

I respectfully request that you reverse this denial and process the claim for payment.

DISCLAIMER: This letter was generated by an automated tool and does not constitute legal advice. Please review all information for accuracy before submitting.

Sincerely,
Jane Smith"""

# New data format: matches denial_database.json structure
TEST_DENIAL_DATABASE = [
    {
        "denial_category": "Prior Authorization",
        "category_id": "prior_authorization",
        "carc_codes": ["197", "15"],
        "description": "The claim was denied because required prior authorization was missing.",
        "tracks": {
            "aca": {
                "regulations": [
                    {
                        "citation": "42 USC 300gg-19",
                        "summary": "Requires internal claims appeals and external review processes for group and individual health coverage.",
                    },
                    {
                        "citation": "29 CFR 2590.715-2719",
                        "summary": "Implements internal claims and appeals and external review processes.",
                    },
                ],
                "appeal_deadline": "Internal appeal: at least 180 days from receipt of the adverse benefit determination.",
                "appeal_process": [
                    "Submit an internal appeal within the deadline.",
                    "Include written comments and supporting documents.",
                    "Request expedited review if urgent.",
                    "If denied, request external review.",
                ],
                "appeal_strategy": "Focus on proving that prior authorization was obtained or should be granted retroactively.",
                "template_key": "prior_auth_aca",
                "escalation": "External review (state or federal). Decisions are binding on the plan.",
                "required_evidence": [
                    "Denial notice or EOB with CARC code",
                    "Prior authorization request and response records",
                    "Treating physician letter",
                ],
            }
        },
        "common_grounds": "Prior authorization was obtained or should be granted retroactively due to medical necessity or emergency.",
    },
    {
        "denial_category": "Coding Error",
        "category_id": "coding_error",
        "carc_codes": ["4", "16"],
        "description": "The claim was denied due to a coding or billing error.",
        "tracks": {
            "aca": {
                "regulations": [
                    {
                        "citation": "42 USC 300gg-19",
                        "summary": "Requires internal claims appeals and external review.",
                    }
                ],
                "appeal_deadline": "180 days.",
                "appeal_process": ["Submit corrected claim or appeal."],
                "appeal_strategy": "Correct the coding error and resubmit.",
                "template_key": "coding_error_aca",
                "escalation": "External review.",
                "required_evidence": ["Corrected claim form"],
            }
        },
        "common_grounds": "The original coding was correct, or the error has been corrected.",
    },
]

TEST_CARC_LOOKUP = {
    "197": "prior_authorization",
    "15": "prior_authorization",
    "4": "coding_error",
    "16": "coding_error",
}

TEST_STATE_CONTACTS = {
    "PA": {
        "state_name": "Pennsylvania",
        "agency": "PA Department of Human Services",
        "appeal_body": "Bureau of Hearings and Appeals",
        "phone": "1-800-692-7462",
        "online_portal": None,
        "mailing_address": "P.O. Box 2675, Harrisburg, PA 17105",
        "notes": "Test data",
    }
}


@pytest.fixture
def sample_denial_text():
    return SAMPLE_DENIAL_TEXT


@pytest.fixture
def sample_extraction_result():
    # Use string confidence (post-conversion) for fixtures used by generation/chat tests
    data = {**SAMPLE_EXTRACTION_JSON, "confidence": "high"}
    return DenialExtractionResult(
        **data,
        raw_text=SAMPLE_DENIAL_TEXT,
    )


@pytest.fixture
def sample_lookup_result():
    return RegulatoryLookupResult(
        carc_definition="The claim was denied because required prior authorization was missing.",
        rarc_definition=None,
        applicable_regulations=[
            RegulationEntry(
                citation="42 USC 300gg-19",
                summary="Requires internal claims appeals and external review processes for group and individual health coverage.",
            ),
            RegulationEntry(
                citation="29 CFR 2590.715-2719",
                summary="Implements internal claims and appeals and external review processes.",
            ),
        ],
        appeal_grounds=["Prior authorization was obtained or should be granted retroactively due to medical necessity or emergency."],
        template_language="APPEAL STRATEGY:\nFocus on proving that prior authorization was obtained or should be granted retroactively.",
        denial_type_matched="prior_authorization",
        appeal_deadline="Internal appeal: at least 180 days from receipt of the adverse benefit determination.",
        appeal_process=[
            "Submit an internal appeal within the deadline.",
            "Include written comments and supporting documents.",
            "Request expedited review if urgent.",
            "If denied, request external review.",
        ],
        appeal_strategy="Focus on proving that prior authorization was obtained or should be granted retroactively.",
        required_evidence=[
            "Denial notice or EOB with CARC code",
            "Prior authorization request and response records",
            "Treating physician letter",
        ],
        escalation="External review (state or federal). Decisions are binding on the plan.",
    )


@pytest.fixture
def test_data_dir():
    """Create a temp directory with valid test JSON data files (new format)."""
    with tempfile.TemporaryDirectory() as tmpdir:
        base = Path(tmpdir)

        with open(base / "denial_database.json", "w") as f:
            json.dump(TEST_DENIAL_DATABASE, f)
        with open(base / "carc_lookup.json", "w") as f:
            json.dump(TEST_CARC_LOOKUP, f)
        with open(base / "state_medicaid_contacts.json", "w") as f:
            json.dump(TEST_STATE_CONTACTS, f)

        yield tmpdir


@pytest.fixture
def empty_data_dir():
    """Create a temp directory with empty/missing data files."""
    with tempfile.TemporaryDirectory() as tmpdir:
        base = Path(tmpdir)

        with open(base / "denial_database.json", "w") as f:
            json.dump([], f)
        with open(base / "carc_lookup.json", "w") as f:
            json.dump({}, f)
        with open(base / "state_medicaid_contacts.json", "w") as f:
            json.dump({}, f)

        yield tmpdir


def _make_mock_gemini_response(text: str):
    """Create a mock Gemini response object."""
    mock_response = MagicMock()
    mock_response.text = text
    return mock_response


@pytest.fixture
def mock_gemini_extraction():
    """Patch Gemini client to return a known extraction JSON."""
    mock_client = MagicMock()
    mock_client.models.generate_content.return_value = _make_mock_gemini_response(
        json.dumps(SAMPLE_EXTRACTION_JSON)
    )
    with patch("app.services.extraction._get_client", return_value=mock_client):
        yield mock_client


@pytest.fixture
def mock_gemini_generation():
    """Patch Gemini client to return a known appeal letter."""
    mock_client = MagicMock()
    mock_client.models.generate_content.return_value = _make_mock_gemini_response(
        SAMPLE_APPEAL_LETTER
    )
    with patch("app.services.generation._get_client", return_value=mock_client):
        yield mock_client


@pytest.fixture
def mock_gemini_chat():
    """Patch Gemini client for chat service."""
    mock_client = MagicMock()
    # Field update detection returns empty (no field changes)
    # Summary returns a simple message
    mock_client.models.generate_content.side_effect = [
        _make_mock_gemini_response("{}"),  # field updates
        _make_mock_gemini_response(SAMPLE_APPEAL_LETTER),  # regenerated letter
        _make_mock_gemini_response("Letter regenerated with your changes."),  # summary
    ]
    with patch("app.services.chat._get_client", return_value=mock_client):
        yield mock_client


@pytest.fixture
def mock_gemini_all(mock_gemini_extraction, mock_gemini_generation, mock_gemini_chat):
    """Patch all Gemini clients."""
    yield


@pytest.fixture
def client(mock_gemini_all):
    """FastAPI TestClient with all Gemini mocked."""
    from app.main import app
    with TestClient(app) as c:
        yield c
