import json
import os
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from fastapi.testclient import TestClient

from app.models.schemas import (
    DenialExtractionResult,
    RegulationEntry,
    RegulatoryLookupResult,
)


SAMPLE_DENIAL_TEXT = """HealthFirst Insurance Company
Claims Department

Date: January 15, 2026

Patient Name: Jane Smith
Member ID: HF-2026-88421
Provider: Dr. Robert Chen, MD
Provider NPI: 1234567890
Claim Number: CLM-2026-00142

Date of Service: December 20, 2025
Procedure Code: CPT 27447 (Total Knee Arthroplasty)

REASON FOR DENIAL:
Your claim has been denied because prior authorization was not obtained.

CARC: 197
RARC: N56

Plan Type: ACA Marketplace (Silver Plan)

Appeal deadline: 180 days from date of denial.
"""

SAMPLE_EXTRACTION_JSON = {
    "carc_code": "197",
    "rarc_code": "N56",
    "cpt_codes": ["27447"],
    "denial_reason": "Prior authorization was not obtained before the service was rendered.",
    "denial_type": "prior_authorization",
    "plan_type": "ACA Marketplace",
    "patient_name": "Jane Smith",
    "patient_id": "HF-2026-88421",
    "provider_name": "Dr. Robert Chen, MD",
    "provider_npi": "1234567890",
    "insurance_company": "HealthFirst Insurance Company",
    "claim_number": "CLM-2026-00142",
    "date_of_service": "2025-12-20",
    "date_of_denial": "2026-01-15",
    "appeal_deadline": "180 days from date of denial",
    "confidence": 0.95,
}

SAMPLE_APPEAL_LETTER = """Dear HealthFirst Insurance Company Appeals Department,

I am writing to formally appeal the denial of claim CLM-2026-00142 for patient Jane Smith (Member ID: HF-2026-88421).

The denied service, CPT 27447 (Total Knee Arthroplasty), was performed on December 20, 2025 by Dr. Robert Chen, MD (NPI: 1234567890).

Your denial, issued January 15, 2026, cites CARC 197 (Precertification/authorization/notification absent) as the reason. I respectfully request reconsideration based on the following grounds:

Under 42 CFR 438.210(d), managed care organizations must have authorization systems with standard and expedited timelines and must allow retroactive authorization in emergency situations.

I respectfully request that you reverse this denial and process the claim for payment.

DISCLAIMER: This letter was generated by an automated tool and does not constitute legal advice. Please review all information for accuracy before submitting.

Sincerely,
Jane Smith"""

TEST_DENIAL_CODES = {
    "CARC": {
        "197": {
            "description": "Precertification/authorization/notification absent",
            "denial_type": "prior_authorization",
            "common_rarc": ["N56"],
        },
        "CO-4": {
            "description": "The procedure code is inconsistent with the modifier used",
            "denial_type": "coding_billing_error",
            "common_rarc": ["MA130"],
        },
    },
    "RARC": {
        "N56": {"description": "Procedure requires prior authorization"},
    },
}

TEST_REGULATIONS = {
    "prior_authorization": [
        {
            "citation": "42 CFR 438.210(d)",
            "title": "Coverage and authorization of services",
            "summary": "MCOs must have authorization systems with standard and expedited timelines and must allow retroactive authorization in emergencies.",
            "relevance": "Insurer must follow proper prior auth procedures",
        }
    ],
}

TEST_APPEAL_GROUNDS = {
    "prior_authorization": [
        "Service was medically necessary and emergent, qualifying for retroactive authorization",
        "Insurer failed to provide adequate notification of prior authorization requirements",
    ],
}

TEST_TEMPLATES = {
    "prior_authorization": {
        "opening": "I am writing to formally appeal the denial of claim {claim_number}.",
        "body": "The denied service, {cpt_codes}, was performed on {date_of_service}.",
        "closing": "I respectfully request that you reverse this denial and process the claim.",
    },
}


@pytest.fixture
def sample_denial_text():
    return SAMPLE_DENIAL_TEXT


@pytest.fixture
def sample_extraction_result():
    return DenialExtractionResult(
        **SAMPLE_EXTRACTION_JSON,
        raw_text=SAMPLE_DENIAL_TEXT,
    )


@pytest.fixture
def sample_lookup_result():
    return RegulatoryLookupResult(
        carc_definition="Precertification/authorization/notification absent",
        rarc_definition="Procedure requires prior authorization",
        applicable_regulations=[
            RegulationEntry(**TEST_REGULATIONS["prior_authorization"][0])
        ],
        appeal_grounds=TEST_APPEAL_GROUNDS["prior_authorization"],
        template_language="I am writing to formally appeal...\n\nThe denied service...\n\nI respectfully request...",
        denial_type_matched="prior_authorization",
    )


@pytest.fixture
def test_data_dir():
    """Create a temp directory with valid test JSON data files."""
    with tempfile.TemporaryDirectory() as tmpdir:
        base = Path(tmpdir)

        (base / "carc_rarc").mkdir()
        (base / "regulations").mkdir()
        (base / "appeal_grounds").mkdir()
        (base / "templates").mkdir()

        with open(base / "carc_rarc" / "denial_codes.json", "w") as f:
            json.dump(TEST_DENIAL_CODES, f)
        with open(base / "regulations" / "aca_regulations.json", "w") as f:
            json.dump(TEST_REGULATIONS, f)
        with open(base / "appeal_grounds" / "grounds_by_denial_type.json", "w") as f:
            json.dump(TEST_APPEAL_GROUNDS, f)
        with open(base / "templates" / "appeal_templates.json", "w") as f:
            json.dump(TEST_TEMPLATES, f)

        yield tmpdir


@pytest.fixture
def empty_data_dir():
    """Create a temp directory with empty JSON data files."""
    with tempfile.TemporaryDirectory() as tmpdir:
        base = Path(tmpdir)

        (base / "carc_rarc").mkdir()
        (base / "regulations").mkdir()
        (base / "appeal_grounds").mkdir()
        (base / "templates").mkdir()

        for path in [
            base / "carc_rarc" / "denial_codes.json",
            base / "regulations" / "aca_regulations.json",
            base / "appeal_grounds" / "grounds_by_denial_type.json",
            base / "templates" / "appeal_templates.json",
        ]:
            with open(path, "w") as f:
                json.dump({}, f)

        yield tmpdir


def _make_mock_gemini_response(text: str):
    """Create a mock Gemini response object."""
    mock_response = MagicMock()
    mock_response.text = text
    return mock_response


@pytest.fixture
def mock_gemini_extraction():
    """Patch Gemini to return a known extraction JSON."""
    mock_model = MagicMock()
    mock_model.generate_content.return_value = _make_mock_gemini_response(
        json.dumps(SAMPLE_EXTRACTION_JSON)
    )
    with patch("app.services.extraction._model", mock_model):
        yield mock_model


@pytest.fixture
def mock_gemini_generation():
    """Patch Gemini to return a known appeal letter."""
    mock_model = MagicMock()
    mock_model.generate_content.return_value = _make_mock_gemini_response(
        SAMPLE_APPEAL_LETTER
    )
    with patch("app.services.generation._model", mock_model):
        yield mock_model


@pytest.fixture
def mock_gemini_both(mock_gemini_extraction, mock_gemini_generation):
    """Patch both Gemini models."""
    yield


@pytest.fixture
def client(mock_gemini_both):
    """FastAPI TestClient with mocked Gemini."""
    from app.main import app
    with TestClient(app) as c:
        yield c
