import logging
import os

from google import genai
from google.genai import types

from app.models.schemas import (
    AppealLetterResponse,
    DenialExtractionResult,
    RegulatoryLookupResult,
)

logger = logging.getLogger(__name__)

MODEL = "gemini-2.5-flash"
_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GEMINI_API_KEY", "")
        if not api_key:
            raise RuntimeError("GEMINI_API_KEY environment variable is not set")
        _client = genai.Client(api_key=api_key)
    return _client


GENERATION_PROMPT = """You are a healthcare insurance appeal letter writer. Generate a professional, formal appeal letter based ONLY on the facts and regulations provided below. Do NOT invent citations or regulations -- use ONLY what is provided.

EXTRACTED CLAIM INFORMATION:
{claim_info}

STATED DENIAL REASON (address this SPECIFICALLY in your argument — do not make generic claims):
{denial_reason}

APPLICABLE REGULATIONS:
{regulations_text}

LEGAL/PROCEDURAL GROUNDS FOR APPEAL:
{grounds_text}

APPEAL DEADLINE:
{appeal_deadline_text}

APPEAL PROCESS:
{appeal_process_text}

REQUIRED EVIDENCE:
{required_evidence_text}

ESCALATION PATH:
{escalation_text}

{template_section}

INSTRUCTIONS:
1. Write the letter FROM THE PATIENT's perspective (first person: "I am writing to appeal..."). The patient is writing to their insurance company. Do NOT write from the provider or doctor's perspective.
2. Address the letter to the insurance company's appeals department.{address_instruction}
3. Cite ONLY the regulations listed above, using their exact citation strings. If no regulations are provided, write a general appeal based on the facts and note that specific regulatory citations should be verified.
4. Reference specific appeal grounds from the list above.
5. CRITICALLY: Build a specific argument that directly addresses the stated denial reason above. Do NOT make vague or generic claims about medical necessity. Instead, argue specifically against the insurer's reasoning (e.g., if they say Level 4 documentation only supports Level 3, argue why the clinical complexity warranted Level 4).
6. Include all relevant patient/claim identifiers.
7. Maintain a professional, assertive but respectful tone.
8. Do NOT include placeholder text like [MISSING], N/A, or None in the letter. If information is not available, simply omit it.
9. When listing supporting evidence, present it as a checklist of documents the patient SHOULD GATHER and include with their appeal submission. Do NOT say these documents are "enclosed" — the patient still needs to collect them.
10. End with a clear request to overturn the denial and mention the right to external review if the internal appeal is denied.
11. Include a disclaimer at the end: "DISCLAIMER: This letter was generated by an automated tool and does not constitute legal advice. Please review all information for accuracy before submitting."

{confidence_caveat}
{additional_instructions}
Return ONLY the letter text, no metadata or explanation."""


def _build_claim_info(extraction: DenialExtractionResult, lookup: RegulatoryLookupResult) -> str:
    """Build claim info section dynamically, omitting null fields."""
    lines = []

    def add(label: str, value: str | None):
        if value:
            lines.append(f"- {label}: {value}")

    add("Patient", extraction.patient_name)
    add("Patient ID", extraction.patient_id)
    add("Provider", extraction.provider_name)
    add("Provider NPI", extraction.provider_npi)
    add("Insurance Company", extraction.insurance_company)
    add("Insurance Company Address", extraction.insurer_address)
    add("Claim Number", extraction.claim_number)
    add("Date of Service", extraction.date_of_service)
    add("Date of Denial", extraction.date_of_denial)
    add("Appeal Deadline", extraction.appeal_deadline)
    if extraction.denied_cpt_codes:
        add("Denied Procedure(s)", ", ".join(extraction.denied_cpt_codes))
    add("Stated Denial Reason", extraction.denial_reason or None)
    add("Denial Type", extraction.denial_type)

    if extraction.carc_code:
        carc_text = extraction.carc_code
        if lookup.carc_definition:
            carc_text += f" ({lookup.carc_definition})"
        add("CARC Code", carc_text)

    if extraction.rarc_code:
        rarc_text = extraction.rarc_code
        if lookup.rarc_definition:
            rarc_text += f" ({lookup.rarc_definition})"
        add("RARC Code", rarc_text)

    return "\n".join(lines) if lines else "No claim information available."


def _format_regulations(lookup: RegulatoryLookupResult) -> str:
    if not lookup.applicable_regulations:
        return "No specific regulations available in the database for this denial type."

    lines = []
    for i, reg in enumerate(lookup.applicable_regulations, 1):
        header = f"{i}. {reg.citation}"
        if reg.title:
            header += f" - {reg.title}"
        lines.append(header)
        lines.append(f"   Summary: {reg.summary}")
        if reg.relevance:
            lines.append(f"   Relevance: {reg.relevance}")
    return "\n".join(lines)


def _format_grounds(lookup: RegulatoryLookupResult) -> str:
    if not lookup.appeal_grounds:
        return "No specific appeal grounds available in the database for this denial type."

    return "\n".join(f"{i}. {g}" for i, g in enumerate(lookup.appeal_grounds, 1))


def _format_template_section(lookup: RegulatoryLookupResult) -> str:
    if lookup.template_language:
        return f"TEMPLATE STRUCTURE (follow this structure but write naturally):\n{lookup.template_language}"
    return ""


async def generate_appeal_letter(
    extraction: DenialExtractionResult,
    lookup: RegulatoryLookupResult,
    additional_context: str = "",
) -> AppealLetterResponse:
    """Stage 3: Use Gemini to compose an appeal letter from extracted facts and regulations."""

    confidence_caveat = ""
    if extraction.confidence != "high":
        confidence_caveat = (
            "NOTE: The system has lower confidence in the denial classification. "
            "Include a paragraph noting that the appeal basis should be verified "
            "by the patient or their healthcare provider before submission."
        )

    address_instruction = ""
    if extraction.insurer_address:
        address_instruction = f" Use this address in the letter header: {extraction.insurer_address}"

    additional_instructions = ""
    if additional_context:
        additional_instructions = f"ADDITIONAL INSTRUCTIONS FROM USER:\n{additional_context}\n"

    appeal_deadline_text = lookup.appeal_deadline or "Not available"
    appeal_process_text = "\n".join(
        f"  {i}. {s}" for i, s in enumerate(lookup.appeal_process, 1)
    ) if lookup.appeal_process else "Not available"
    required_evidence_text = "\n".join(
        f"  - {e}" for e in lookup.required_evidence
    ) if lookup.required_evidence else "Not available"
    escalation_text = lookup.escalation or "Not available"

    prompt = GENERATION_PROMPT.format(
        claim_info=_build_claim_info(extraction, lookup),
        denial_reason=extraction.denial_reason or "Not specified",
        regulations_text=_format_regulations(lookup),
        grounds_text=_format_grounds(lookup),
        appeal_deadline_text=appeal_deadline_text,
        appeal_process_text=appeal_process_text,
        required_evidence_text=required_evidence_text,
        escalation_text=escalation_text,
        template_section=_format_template_section(lookup),
        address_instruction=address_instruction,
        confidence_caveat=confidence_caveat,
        additional_instructions=additional_instructions,
    )

    try:
        response = _get_client().models.generate_content(
            model=MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(temperature=0.3),
        )
    except Exception as e:
        logger.error(f"Gemini generation call failed: {e}")
        raise RuntimeError(f"LLM generation failed: {e}") from e

    letter_text = response.text.strip()

    # Extract which citations were actually used in the letter
    citations_used = []
    for reg in lookup.applicable_regulations:
        if reg.citation in letter_text:
            citations_used.append(reg.citation)

    confidence_note = None
    if extraction.confidence != "high":
        confidence_note = (
            f"Extraction confidence is {extraction.confidence}. "
            "Please verify the denial classification and appeal basis before submitting."
        )

    return AppealLetterResponse(
        letter_text=letter_text,
        citations_used=citations_used,
        confidence_note=confidence_note,
        denial_type=extraction.denial_type,
    )
