import logging
import os

from google import genai
from google.genai import types

from app.models.schemas import (
    AppealLetterResponse,
    DenialExtractionResult,
    RegulatoryLookupResult,
)

logger = logging.getLogger(__name__)

MODEL = "gemini-2.5-flash"
_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GEMINI_API_KEY", "")
        if not api_key:
            raise RuntimeError("GEMINI_API_KEY environment variable is not set")
        _client = genai.Client(api_key=api_key)
    return _client

GENERATION_PROMPT = """You are a healthcare insurance appeal letter writer. Generate a professional, formal appeal letter based ONLY on the facts and regulations provided below. Do NOT invent citations or regulations -- use ONLY what is provided.

EXTRACTED CLAIM INFORMATION:
- Patient: {patient_name}
- Patient ID: {patient_id}
- Provider: {provider_name}
- Insurance Company: {insurance_company}
- Claim Number: {claim_number}
- Date of Service: {date_of_service}
- Date of Denial: {date_of_denial}
- Appeal Deadline: {appeal_deadline}
- Denied Procedure(s): {cpt_codes}
- Stated Denial Reason: {denial_reason}
- Denial Type: {denial_type}
- CARC Code: {carc_code} - {carc_definition}
- RARC Code: {rarc_code} - {rarc_definition}

APPLICABLE REGULATIONS:
{regulations_text}

LEGAL/PROCEDURAL GROUNDS FOR APPEAL:
{grounds_text}

APPEAL DEADLINE:
{appeal_deadline_text}

APPEAL PROCESS:
{appeal_process_text}

REQUIRED EVIDENCE:
{required_evidence_text}

ESCALATION PATH:
{escalation_text}

{template_section}

INSTRUCTIONS:
1. Write a formal appeal letter addressed to the insurance company's appeals department.
2. Cite ONLY the regulations listed above, using their exact citation strings. If no regulations are provided, write a general appeal based on the facts and note that specific regulatory citations should be verified.
3. Reference specific appeal grounds from the list above.
4. Include all relevant patient/claim identifiers.
5. Maintain a professional, assertive but respectful tone.
6. If any critical information is missing (shown as None), note it with [MISSING: field name].
7. End with a clear request to overturn the denial and mention the right to external review if the internal appeal is denied.
8. Include a disclaimer at the end: "DISCLAIMER: This letter was generated by an automated tool and does not constitute legal advice. Please review all information for accuracy before submitting."

{confidence_caveat}

Return ONLY the letter text, no metadata or explanation."""


def _format_regulations(lookup: RegulatoryLookupResult) -> str:
    if not lookup.applicable_regulations:
        return "No specific regulations available in the database for this denial type."

    lines = []
    for i, reg in enumerate(lookup.applicable_regulations, 1):
        header = f"{i}. {reg.citation}"
        if reg.title:
            header += f" - {reg.title}"
        lines.append(header)
        lines.append(f"   Summary: {reg.summary}")
        if reg.relevance:
            lines.append(f"   Relevance: {reg.relevance}")
    return "\n".join(lines)


def _format_grounds(lookup: RegulatoryLookupResult) -> str:
    if not lookup.appeal_grounds:
        return "No specific appeal grounds available in the database for this denial type."

    return "\n".join(f"{i}. {g}" for i, g in enumerate(lookup.appeal_grounds, 1))


def _format_template_section(lookup: RegulatoryLookupResult) -> str:
    if lookup.template_language:
        return f"TEMPLATE STRUCTURE (follow this structure but write naturally):\n{lookup.template_language}"
    return ""


async def generate_appeal_letter(
    extraction: DenialExtractionResult,
    lookup: RegulatoryLookupResult,
) -> AppealLetterResponse:
    """Stage 3: Use Gemini to compose an appeal letter from extracted facts and regulations."""

    confidence_caveat = ""
    if extraction.confidence < 0.7:
        confidence_caveat = (
            "NOTE: The system has low confidence in the denial classification. "
            "Include a paragraph noting that the appeal basis should be verified "
            "by the patient or their healthcare provider before submission."
        )

    # Format new lookup fields
    appeal_deadline_text = lookup.appeal_deadline or "Not available"
    appeal_process_text = "\n".join(
        f"  {i}. {s}" for i, s in enumerate(lookup.appeal_process, 1)
    ) if lookup.appeal_process else "Not available"
    required_evidence_text = "\n".join(
        f"  - {e}" for e in lookup.required_evidence
    ) if lookup.required_evidence else "Not available"
    escalation_text = lookup.escalation or "Not available"

    prompt = GENERATION_PROMPT.format(
        patient_name=extraction.patient_name or "None",
        patient_id=extraction.patient_id or "None",
        provider_name=extraction.provider_name or "None",
        insurance_company=extraction.insurance_company or "None",
        claim_number=extraction.claim_number or "None",
        date_of_service=extraction.date_of_service or "None",
        date_of_denial=extraction.date_of_denial or "None",
        appeal_deadline=extraction.appeal_deadline or "None",
        cpt_codes=", ".join(extraction.cpt_codes) if extraction.cpt_codes else "None",
        denial_reason=extraction.denial_reason or "None",
        denial_type=extraction.denial_type or "Unknown",
        carc_code=extraction.carc_code or "None",
        carc_definition=lookup.carc_definition or "N/A",
        rarc_code=extraction.rarc_code or "None",
        rarc_definition=lookup.rarc_definition or "N/A",
        regulations_text=_format_regulations(lookup),
        grounds_text=_format_grounds(lookup),
        appeal_deadline_text=appeal_deadline_text,
        appeal_process_text=appeal_process_text,
        required_evidence_text=required_evidence_text,
        escalation_text=escalation_text,
        template_section=_format_template_section(lookup),
        confidence_caveat=confidence_caveat,
    )

    try:
        response = _get_client().models.generate_content(
            model=MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(temperature=0.3),
        )
    except Exception as e:
        logger.error(f"Gemini generation call failed: {e}")
        raise RuntimeError(f"LLM generation failed: {e}") from e

    letter_text = response.text.strip()

    # Extract which citations were actually used in the letter
    citations_used = []
    for reg in lookup.applicable_regulations:
        if reg.citation in letter_text:
            citations_used.append(reg.citation)

    confidence_note = None
    if extraction.confidence < 0.7:
        confidence_note = (
            f"Extraction confidence is {extraction.confidence:.0%}. "
            "Please verify the denial classification and appeal basis before submitting."
        )

    return AppealLetterResponse(
        letter_text=letter_text,
        citations_used=citations_used,
        confidence_note=confidence_note,
        denial_type=extraction.denial_type,
    )
